SELECT EXECUTIONS , DISK_READS, BUFFER_GETS, 

ROUND((BUFFER_GETS-DISK_READS)/BUFFER_GETS,2) Hit_radio, 

ROUND(DISK_READS/EXECUTIONS,2) Reads_per_run, 

SQL_TEXT 

FROM V$SQLAREA 

WHERE EXECUTIONS>0 

AND BUFFER_GETS > 0 

AND (BUFFER_GETS-DISK_READS)/BUFFER_GETS < 0.8 

ORDER BY 4 DESC; 
