SELECT ADDRESS,
       SUBSTR(SQL_TEXT, 1, 2000) TEXT,
       BUFFER_GETS,
       EXECUTIONS,
       hash_value,
       BUFFER_GETS / EXECUTIONS AVG 　　
FROM V$SQLAREA 　　
WHERE EXECUTIONS > 0AND BUFFER_GETS > 100000 
ORDER BY 6 DESC;
