select TABLE_NAME, TABLE_OWNER, COUNT(INDEX_NAME)
  from dba_indexes
 where owner not in ('SYS', 'SYSTEM')
 GROUP BY TABLE_NAME, TABLE_OWNER
 HAVING COUNT(INDEX_NAME)>=3
 ORDER BY COUNT(INDEX_NAME) DESC;


