SELECT B.DATABASE_NAME,
       A.OWNER,
       A.TABLE_NAME,
       TO_CHAR(A.ANALYZE_DATE, 'yyyy-mm-dd hh24:mm:ss') PLAN_ANA_TIME
  FROM PERFSTAT.ANALYZE_TABLELIST A, PERFSTAT.DATABASE_INFO B
 WHERE VALID = 1
   AND A.FK_SERVER_ID = B.DATABASE_ID
   AND B.DATABASE_NAME = '$1'
   AND TO_CHAR(ANALYZE_DATE, 'yyyymmddhh24') LIKE '$2%'



